name: Build Quartz Site

on:
  push:
    branches:
      - main
    paths:
      - content/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Downloads the repo on the VM
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            content
            quartz

        # Prepares the VM environment for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5

        # Builds the website from markdown files using Quartz
      - name: Build
        uses: konstfish/quartz-build-action@v7
        with:
          source: content           # your source
          destination: public       # where output goes
          page_title: "Kiwi Docs"   # website title

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages